### ISSUE TITLE
no function clause matching in String.split/3

### ISSUE THREAD

**Issue by grych** [wojtekmach/changelog#2]
```
kim:grych<~>% changelog drab             
** (FunctionClauseError) no function clause matching in String.split/3    
    
    The following arguments were given to String.split/3:
    
        # 1
        nil
    
        # 2
        "\n"
    
        # 3
        [trim: true]
    
    (elixir) lib/string.ex:383: String.split/3
    (changelog) lib/changelog/parser.ex:6: Changelog.Parser.parse!/1
    (changelog) lib/changelog/cli.ex:24: Changelog.CLI.main/1
    (elixir) lib/kernel/cli.ex:105: anonymous fn/3 in Kernel.CLI.exec_fun/2

```

```
kim:grych<~>% elixir -v
Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.6.0 (compiled with OTP 20)

```

**Comment by wojtekmach** [comment]
thanks for the report!

The issue is your package does not include CHANGELOG in the tarball [1], but I definitely need to add better error handling.

[1] https://github.com/grych/drab/blob/v0.7.0/mix.exs#L68

**Comment by grych** [comment]
Maybe you could search for the changelog in github in such case? Of course only if the github link is given in the `package/0`.

I believe there is more packages which does not include changelog (I don't see the point why should it be included :))

**Comment by wojtekmach** [comment]
yup, cool idea!

**Comment by wojtekmach** [comment]
I added basic error message, I'll explore your idea about falling back to GitHub url in the future. Thanks again!

FWIW I do think packages should ship with their changelogs, e.g. Ecto maintain changelogs per vX.Y (e.g. 2.0 and 2.1 are completely different) so it's very useful that it's in the tarball.
